name: Check semver compatibility with previous versions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  semver:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check semver compatibility with previous versions
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          rust-toolchain: manual
